### PESSOA ID: 8, 9, 10, 11, 12
###LOCAIS ID: 1, 3, 4

### Create Local Coleta
POST http://localhost:4000/distribuicao
Content-Type: application/json

{
  "unidade_id": 1,
  "produto_id": 1,
  "date": "22/10/2022"
}
### Create Local Coleta
POST http://localhost:4000/distribuicao
Content-Type: application/json

{
  "unidade_id": 2,
  "produto_id": 2,
  "date": "21/10/2022"
}


### Create Local Coleta
POST http://localhost:4000/distribuicao
Content-Type: application/json

{
  "unidade_id": 3,
  "produto_id": 3,
  "date": "29/09/2022"
}

